# Generated by Django 4.2.11 on 2024-06-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/books/')),
                ('borrowing_price', models.IntegerField()),
                ('category', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non Fiction'), ('novel', 'Novel'), ('technology', 'Technology'), ('science', 'Science'), ('health', 'Health'), ('selfdevelopment', 'Self Development')], max_length=100)),
            ],
        ),
    ]
